FROM python:3.10.8-slim

RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY ./parser ./
COPY analyze_tg_news.session ./
COPY analyze_tg_news.session ./

RUN pip install uv==0.8.17 --no-cache-dir

RUN uv sync \
    --no-dev \
    --group=parser \
    --no-cache